services:
  db:
    image: postgres:18.1-alpine
    container_name: roomie_lms_postgres
    restart: always
    environment:
      POSTGRES_USER: roomie_admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: roomie_lms_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: